# Generated by Django 3.0.3 on 2020-03-15 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cerrada', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.IntegerField(choices=[(0, 'comentario'), (1, 'pregunta'), (2, 'respuesta')], null=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('cuerpo', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Publicacion')),
                ('votos_positivos', models.PositiveIntegerField()),
                ('votos_negativos', models.PositiveIntegerField()),
                ('aceptada', models.BooleanField(default=False)),
                ('discusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Discusion')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=('qa.publicacion', models.Model),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Publicacion')),
                ('titulo', models.CharField(max_length=150)),
                ('discusion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qa.Discusion')),
                ('etiquetas', models.ManyToManyField(to='qa.Etiqueta')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=('qa.publicacion',),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Publicacion')),
                ('votos_positivos', models.PositiveIntegerField()),
                ('votos_negativos', models.PositiveIntegerField()),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='qa.Publicacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('qa.publicacion', models.Model),
        ),
    ]
