# Generated by Django 3.0.3 on 2020-03-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='usuario',
            new_name='autor',
        ),
    ]
