# Generated by Django 2.2.3 on 2020-03-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200315_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='votos_negativos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='votos_positivos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='votos_negativos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='votos_positivos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='qa.Etiqueta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='discusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='qa.Discusion'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='votos_negativos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='votos_positivos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
