# Generated by Django 3.0.3 on 2020-04-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20200319_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discusion',
            options={'ordering': ['-pregunta__created']},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='votos_positivos',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='votos_positivos',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='votos_positivos',
        ),
    ]
