# Generated by Django 3.0.3 on 2020-04-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20200416_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='votos_negativos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='votos_positivos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
